### ISSUE TITLE
Proses dari  PR to CO

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_saudara#1]
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/96053043/153807463-bce956f6-6761-4277-be0e-39d164748471.png">
 

https://pull.winsoft.co.id/commande/card.php

**Comment by 1ocate** [comment]
Relection #4

**Comment by 1ocate** [comment]
change 'llx_commandedet_extrafield' 'pocustomer' column allow 'Null'
