### ISSUE TITLE
ini di proposal request, ditampilan ga keluar harganya 

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_saudara#11]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/96053043/157639175-937b6534-9c49-4746-b072-12683f80786f.png">

**Comment by 1ocate** [comment]
Next time please detail menu name, because this is vender proposal.

**Comment by 1ocate** [comment]
This is problem because not active document.
How make active, please fallow be low.
<img width="1042" alt="Screen Shot 2022-03-13 at 7 00 52 PM" src="https://user-images.githubusercontent.com/29521447/158058552-49ee7c5c-e725-490b-a443-86a29051678e.png">
