### ISSUE TITLE
CUSTOMER REF GA JALAN, ga keluar  - input dari stocks, tapi pas penamaan di customer REF ga keluar

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_saudara#12]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/96053043/157639299-6b1530f2-6f3c-439d-9e6b-d6b4ca9bbf99.png">

<img width="609" alt="image" src="https://user-images.githubusercontent.com/96053043/157639333-b53bd5c9-2300-4b06-adbc-92226c319a56.png">

**Comment by 1ocate** [comment]
This is relection #11 

please fallow this

<img width="1031" alt="Screen Shot 2022-03-13 at 7 12 32 PM" src="https://user-images.githubusercontent.com/29521447/158058871-8fc6959f-3307-4eaa-afbf-b0f8f0f0ce71.png">
