### ISSUE TITLE
boleh info. -> cara logo cap di (  PROPOSAL HARGA -> Minta kasih cap logo PT saudara baru international ) 

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_saudara#13]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/96053043/157639774-0dc78d1b-a7e6-4d35-8aa1-67817c1ce66e.png">

**Comment by 1ocate** [comment]
please make stamp for Pt saudara

**Comment by kevinsunjaya** [comment]
besok saya kasih ya

**Comment by kevinsunjaya** [comment]
![WhatsApp Image 2022-03-25 at 13 11 27](https://user-images.githubusercontent.com/96053043/160065315-7f398136-ac27-4f23-a5ab-b3cd34eafc0f.jpeg)
[WhatsApp Image 2022-03-25 at 9.46.25 AM.pdf](https://github.com/wglobalindo/erp_saudara/files/8347959/WhatsApp.Image.2022-03-25.at.9.46.25.AM.pdf)

**Comment by 1ocate** [comment]
please check @kevinsunjaya
