### ISSUE TITLE
Minta MARGIN RATE di invoice, comercial ,  proposal

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_saudara#14]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/96053043/157640019-0224b9e3-6287-4ab7-97d7-c007daacba3a.png">

**Comment by 1ocate** [comment]
what is margin rate?

**Comment by 1ocate** [comment]
This is setting for margin rate display
[Setting margin](https://sdr.winsoft.co.id/margin/admin/margin.php?save_lastsearch_values=1&backtopage=%2Fadmin%2Fmodules.php%3Fsearch_nature%3D%26search_version%3D%26search_status%3D)

<img width="1023" alt="Screen Shot 2022-03-13 at 7 19 11 PM" src="https://user-images.githubusercontent.com/29521447/158059074-9a319915-1e26-4646-ae94-78bd2a44cb4b.png">
