### ISSUE TITLE
TIDAK BISA ADDING ( STOCKS AUTOMATIC  ) DARI  CREATE PURCHASE ORDER

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_saudara#15]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/96053043/157640630-78a70ee2-0c1e-4b3d-ad84-744cbd3716b5.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/96053043/157640661-9aea6e1f-7108-41f6-bf6a-8786e5b6c5b1.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/96053043/157640681-e1deafc3-e7bb-440a-add7-f41df9fa144a.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/96053043/157640645-3d46e589-7a1e-4fbf-8a55-95906fe76c92.png">

**Comment by 1ocate** [comment]
This setting need from here

[Stock setting](https://sdr.winsoft.co.id/admin/stock.php?save_lastsearch_values=1&backtopage=%2Fadmin%2Fmodules.php%3Fsearch_nature%3D%26search_version%3D%26search_status%3D)

<img width="1031" alt="Screen Shot 2022-03-13 at 7 23 11 PM" src="https://user-images.githubusercontent.com/29521447/158059236-9f7dbcf5-ad63-4dfc-82a1-3dc94ae0d804.png">
