### ISSUE TITLE
boleh saat di invoice - doc templatenya  : tambahkan 1 menu format? misalkan namanya : iNVOICE NO TAX

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_saudara#17]
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/96053043/159757760-72282763-a409-48c9-910b-c28fdec303d3.png">

tulisan PT saudara baru international. -> menjadi SAUDARA BARU MACHINERY

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/96053043/159757966-f17e8f51-1651-4525-92b7-ce1fb9a7297f.png">

**Comment by 1ocate** [comment]
this is for only saudara baru atau pt winsoft juga?
