### ISSUE TITLE
dikolom unit di proposal comercial -> PR2202-0086 -> wrong number ( decimal)

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_saudara#3]
https://pull.winsoft.co.id/comm/propal/card.php?id=108&action=confirm_validate&confirm=yes&token=e8cfeddbf7914b1766ab38aab782a1fb

<img width="721" alt="image" src="https://user-images.githubusercontent.com/96053043/153821711-f9099c0d-3a30-44c5-a8a7-e1c8a55ad0bd.png">

di unit  : 33,685.155. -> jadi 336.851

**Comment by 1ocate** [comment]
This is problem setting decimal
<img width="1030" alt="Screen Shot 2022-02-14 at 7 14 51 PM" src="https://user-images.githubusercontent.com/29521447/153862844-a0112171-8501-49c1-bee7-9aeed40d007b.png">

This is correct setting
<img width="1042" alt="Screen Shot 2022-02-14 at 7 14 37 PM" src="https://user-images.githubusercontent.com/29521447/153863215-ec35bf68-9e5b-4170-8624-9e5217d6b41d.png">

@kevinsunjaya please check again and please close issue.
Thanks.

**Comment by kevinsunjaya** [comment]
thank minsoo for your information
