### ISSUE TITLE
email proposal price -> sdrbaru -> ini salah email password?

### ISSUE THREAD

**Issue by kevinsunjaya** [wglobalindo/erp_saudara#5]
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/96053043/154012235-a0dc7305-a44e-435e-aa29-c7453210d2c8.png">

**Comment by 1ocate** [comment]
Try this. https://kinsta.com/blog/gmail-smtp-server/

**Comment by kevinsunjaya** [comment]
bisa samakan seperti wglobalindo@gmail.com ga ya minsoo settingnya?? ?? kalaui pakai thrparty lain , saya agak bingung . maaf

**Comment by 1ocate** [comment]
> bisa samakan seperti [wglobalindo@gmail.com](mailto:wglobalindo@gmail.com) ga ya minsoo settingnya?? ?? kalaui pakai thrparty lain , saya agak bingung . maaf

sudah baca ini belum?

 https://kinsta.com/blog/gmail-smtp-server/

when you fallow this use your sdrbaru gmail account. get password api.
